<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\ReservationController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file contains all the web routes for the Vehicle Rental System.
| Routes are organized by access level: public, authenticated, and admin.
| Each route group has appropriate middleware for security and access control.
|
| Route Structure:
| - Public routes: Accessible to all users (welcome page, vehicle browsing)
| - Authenticated routes: Require user login (reservations, profile)
| - Admin routes: Require admin privileges (management functions)
|
*/

// ============================================================================
// PUBLIC ROUTES (No authentication required)
// ============================================================================

/**
 * Welcome Page - Main landing page with vehicle catalog
 * Displays all available vehicles for public viewing
 */
Route::get('/', [HomeController::class, 'welcome'])->name('welcome')->withoutMiddleware('auth');

/**
 * Vehicle Catalog - Public vehicle browsing
 * Allows users to view all vehicles without authentication
 */
Route::get('/vehicles', [VehicleController::class, 'index'])->name('vehicles.index');

/**
 * Vehicle Details - Individual vehicle information
 * Shows detailed information about a specific vehicle
 */
Route::get('/vehicles/{vehicle}', [VehicleController::class, 'show'])->name('vehicles.show');

// ============================================================================
// AUTHENTICATION ROUTES
// ============================================================================

/**
 * Laravel UI Authentication Routes
 * Includes: login, register, password reset, email verification
 * These routes are automatically generated by Laravel UI
 */
Auth::routes();

// ============================================================================
// AUTHENTICATED USER ROUTES (Require login)
// ============================================================================

/**
 * User Dashboard - Main dashboard for logged-in users
 * Provides overview of user's reservations and account information
 */
Route::get('/home', [HomeController::class, 'index'])->name('home');

/**
 * Profile Management Routes
 * Allows users to view and edit their profile information
 */
Route::middleware(['auth'])->group(function () {
    // Profile routes
    Route::get('/profile', [ProfileController::class, 'show'])->name('profile.show');
    Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');

    /**
     * Reservation Management Routes
     * Full CRUD operations for user reservations
     * - index: List user's reservations
     * - create: Show reservation form
     * - store: Save new reservation
     * - show: Display reservation details
     * - edit: Show edit form
     * - update: Update reservation
     * - destroy: Cancel reservation
     */
    Route::resource('reservations', ReservationController::class);
});

// ============================================================================
// ADMIN ROUTES (Require admin privileges)
// ============================================================================

/**
 * Admin Panel Routes
 * All admin routes are prefixed with 'admin' and require both
 * authentication and admin middleware for security.
 */
Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {
    
    /**
     * Admin Dashboard
     * Overview of system statistics and recent activities
     */
    Route::get('/dashboard', [AdminController::class, 'dashboard'])->name('dashboard');
    
    /**
     * Vehicle Management Routes
     * Complete CRUD operations for vehicle management
     */
    Route::get('/vehicles', [AdminController::class, 'vehicles'])->name('vehicles.index');
    Route::get('/vehicles/create', [AdminController::class, 'createVehicle'])->name('vehicles.create');
    Route::post('/vehicles', [AdminController::class, 'storeVehicle'])->name('vehicles.store');
    Route::get('/vehicles/{vehicle}/edit', [AdminController::class, 'editVehicle'])->name('vehicles.edit');
    Route::put('/vehicles/{vehicle}', [AdminController::class, 'updateVehicle'])->name('vehicles.update');
    Route::delete('/vehicles/{vehicle}', [AdminController::class, 'destroyVehicle'])->name('vehicles.destroy');
    
    /**
     * Reservation Management Routes
     * Admin functions for managing all reservations
     */
    Route::get('/reservations', [AdminController::class, 'reservations'])->name('reservations.index');
    Route::delete('/reservations/{reservation}', [AdminController::class, 'destroyReservation'])->name('reservations.destroy');
    Route::post('/reservations/{reservation}/approve', [AdminController::class, 'approveReservation'])->name('reservations.approve');
    Route::post('/reservations/{reservation}/reject', [AdminController::class, 'rejectReservation'])->name('reservations.reject');
    
    /**
     * User Management Routes
     * Complete CRUD operations for user management
     * - index: List all users
     * - create: Show user creation form
     * - store: Save new user
     * - show: Display user details
     * - edit: Show edit form
     * - update: Update user information
     * - destroy: Delete user account
     */
    Route::resource('users', UserController::class);
});
